openapi: 3.0.1
info:
  title: callClassMediator
  description: API Definition of callClassMediator
  version: 1.0.0
servers:
- url: http://localhost:8290/uppercase
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
